version: '3.1'

services: 
  database: 
    platform: linux/amd64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=test1234*
      - MYSQL_DATABASE=infrascrum
      - MYSQL_USER=infrascrumUser
      - MYSQL_PASSWORD=test1234*